\documentclass[12pt,a4paper]{paper}
\usepackage[utf8]{inputenc}
\usepackage[english]{babel}
\usepackage{amsmath}
\usepackage{enumitem}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{amsmath}
\usepackage{tikz}
\usepackage{mathdots}
\usepackage{yhmath}
\usepackage{cancel}
\usepackage{color}
\usepackage{siunitx}
\usepackage{array}
\usepackage{multirow}
\usepackage{amssymb}
\usepackage{gensymb}
\usepackage{tabularx}
\usepackage{booktabs}
\usetikzlibrary{fadings}
\usepackage[left=2cm,right=2cm,top=2cm,bottom=2cm]{geometry}
\begin{document}
\title{STAT646 - Homework 5\\\small{Daniel Osorio - dcosorioh@tamu.edu\\Department of Veterinary Integrative Biosciences\\Texas A\&M University}}
\maketitle
\SweaveOpts{concordance=TRUE}
\begin{enumerate}
\item Consider a genome that consists of 1,000 bases. The genome is organized into 20 genes, each
of length 50 bases. The first 50 bases in the genome correspond to gene one, the next 50
bases to gene two, etc. In a particular sample containing mRNA transcripts from this genome,
suppose there are 25 mRNA copies of gene 5, 60 mRNA copies of gene 10, and 40 mRNA
copies of gene 15; none of the other genes are expressed. We apply NGS to create sequencing
reads of length 10 bases. We then align the reads back to the genome and use the resulting
read counts to quantify expression for each gene. Follow the instructions below to conduct a
simulation. For grading purposes, you need only provide your R code, the figure described in
part (e), and the read count table described in part (f).
\begin{enumerate}
\item Create the simulated genome by:
<<>>=
set.seed(101)
genome <- paste(sample(c("A", "C", "T", "G"), 1000, replace = TRUE),
collapse = "")
@
\item Create the fragments to be sequenced. For transcript i, randomly pick a location in
the transcript at which to break. Once a break has been created, you have two smaller
fragments. If a fragment is less than our desired read length of 10, throw it away. If a
fragment is of length 10, 11, . . ., 14, its first 10 bases will be sequenced (so, it does not
need to be fragmented any further). If a fragment is of length 15 bases or greater, it will
be fragmented again. Repeat this sequence until you are left only with short (length $\in$
[10, 14]) fragments that are ready to be sequenced.
\item Create the sequenced reads. For fragment j, create a sequencing read by reading off
the genomic sequence corresponding to the first 10 bases of this fragment, allowing for
sequencing errors to occur in 5\% of all base calls.
\item Align the reads to the genome. For this, use the pairwiseAlignment function from
Biostrings to do local alignment. Reward a base match with a score of +1, penalize a
base mismatch with a score of -1, and penalize a gap with a score of -10 (use gapOpening
= 0 and gapExtension = -10 in pairwiseAlignment). Use the randomization based test
to assign a p-value to the alignment of each read, and only keep the reads that align with
p-values < 0.05; to keep the computation time down, just do B = 100 randomizations,
instead of the B = 1,000 that we did in the classroom examples.
\item Tabulate the number of times each base in the genome was covered by one or more of
the aligned reads. Create a dot plot to visualize the coverages. By ?dot plot,? I just
mean a traditional dot plot in statistics not the specialized plot we made for comparing
two sequences. For example, suppose there are 14 reads that were aligned to overlap
with base k in the genome. Then, you would put 14 dots, one above the other, at the kth
location along the horizontal axis. Figure 1 on page 4 shows an example, for a scenario
in which there are just two genes.
\item Tabulate the number of reads that overlapped, at least partially, with each of the three
expressed genes. For example, if 50 of the sequenced reads overlapped, at at least one
base, with gene 5, the read count for gene 5 would be 50.
\end{enumerate}
\item Context = “hammer” RNA-Seq data. These are read counts for ENSEMBL genes in rats
under two conditions: (1) spinal nerve ligation (SNL), which induces chronic neuropathic
pain, and (2) normal. We have four samples in each condition, two each at 2 weeks and 2
months after start (SNL was done at start in the SNL rats).
\begin{center}
http://www.ncbi.nlm.nih.gov/pubmed?term=20452967
\end{center}
Use DESeq2 to analyze the data:
\begin{enumerate}
\item On the “rlog”-transformed counts:
\begin{enumerate}
\item Carry out hierarchical clustering, using Euclidean distance and complete linkage.
Provide the resulting dendrogram and scree plots. How many clusters would you
say there are? Interpret the clusters with respect to the meta data.
\item Carry out principal component analysis to explore structure among the rats(columns).
How much variation do the first two PCs account for? Interpret the eigenvectors
with respect to the meta data.
\end{enumerate}
\item As we have two factors (one each for treatment group (SNL vs. normal) and time (2
weeks vs. 2 months)), consider the following linear model for gene k’s counts:
\end{enumerate}
\end{enumerate}
\end{document}